/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0F1A24',
        'on-primary': '#ffffff',
        'primary-container': '#0F1A24',
        'primary-fixed': '#d8e4f2',
        'primary-fixed-dim': '#bcc8d5',
        'on-primary-fixed': '#121d27',
        'on-primary-fixed-variant': '#3d4853',
        secondary: '#C8A96A',
        'secondary-container': '#fedb98',
        'secondary-fixed': '#ffdf9f',
        'secondary-fixed-dim': '#e3c281',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#785f28',
        'on-secondary-fixed': '#261a00',
        'on-secondary-fixed-variant': '#5a430e',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#111d23',
        'tertiary-fixed': '#d7e4ec',
        'tertiary-fixed-dim': '#bbc8d0',
        'on-tertiary-fixed': '#111d23',
        'on-tertiary-fixed-variant': '#3c494f',
        surface: '#F8F5EF',
        background: '#F8F5EF',
        'on-background': '#1c1c18',
        'surface-bright': '#F8F5EF',
        'surface-dim': '#dcdad4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ed',
        'surface-container': '#f0eee8',
        'surface-container-high': '#ebe8e2',
        'surface-container-highest': '#e5e2dc',
        'surface-variant': '#e5e2dc',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#44474b',
        'inverse-surface': '#31312d',
        'inverse-on-surface': '#f3f0ea',
        'surface-tint': '#545f6b',
        outline: '#74777c',
        'outline-variant': '#c4c6cb',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        bone: '#F8F5EF',
        ink: '#1c1c18',
      },
      fontFamily: {
        serif: ['Playfair Display', 'ui-serif', 'Georgia', 'serif'],
        sans: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'display-lg': ['Playfair Display'],
        'headline-lg': ['Playfair Display'],
        'headline-md': ['Playfair Display'],
        'headline-lg-mobile': ['Playfair Display'],
        'body-lg': ['Manrope'],
        'body-md': ['Manrope'],
        'label-caps': ['Manrope'],
      },
      fontSize: {
        'display-xl': ['clamp(3.5rem, 8vw, 7rem)', { lineHeight: '0.95', letterSpacing: '-0.03em' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-md': ['clamp(2rem, 4vw, 3.25rem)', { lineHeight: '1.08', letterSpacing: '-0.02em' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.15em', fontWeight: '600' }],
        'title': ['1.125rem', { lineHeight: '1.4', letterSpacing: '0' }],
        'headline': ['clamp(1.5rem, 2.5vw, 2rem)', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'body': ['1rem', { lineHeight: '1.6', letterSpacing: '0.005em' }],
        'body-sm': ['0.9375rem', { lineHeight: '1.55', letterSpacing: '0.005em' }],
      },
      letterSpacing: {
        tight: '-0.02em',
        tighter: '-0.03em',
        wide: '0.08em',
        wider: '0.12em',
        widest: '0.2em',
      },
      spacing: {
        unit: '8px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '80px',
        'margin-mobile': '20px',
        'section-gap': '120px',
        '18': '4.5rem',
        '22': '5.5rem',
        '30': '7.5rem',
        '38': '9.5rem',
      },
      boxShadow: {
        'ambient': '0 30px 60px -20px rgba(28, 28, 25, 0.08)',
        'ambient-sm': '0 20px 40px -15px rgba(28, 28, 25, 0.06)',
        'float': '0 40px 80px -30px rgba(28, 28, 25, 0.1)',
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        'fade-up': 'fadeUp 1s cubic-bezier(0.22, 1, 0.36, 1) both',
        'fade-in': 'fadeIn 1.2s ease-out both',
        'reveal': 'reveal 1.4s cubic-bezier(0.22, 1, 0.36, 1) both',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        reveal: {
          '0%': { opacity: '0', transform: 'scale(1.04)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
